docs/rest-api.rst
mora/app.py
mora/service.py
tests/test_integration_service.py

Documentation for the new layer is available at [RTD](http://mora.readthedocs.io/en/feature-20869_service_organisation/docs/rest-api.html#service-layer).

add simple reimplementations of organisation and org. unit

---

mora/service/employee.py
mora/service/keys.py
mora/service/leave.py
mora/service/mapping.py
tests/fixtures/create_organisationfunktion_orlov.json
tests/test_integration_leave.py
tests/test_integration_service.py
tests/util.py

It doesn't use the get_valid_from/get_valid_to functions from common yet, as it requires a rewrite of some things.
I'll do that later for all the org funk functions in one go.

Implemented writing API for leave

---

mora/service/association.py
mora/service/employee.py
mora/service/engagement.py
mora/service/keys.py
mora/service/role.py
tests/test_integration_importing.py
tests/test_integration_service.py

Generalized existing reading code slightly to facilitate this.

Implemented reading for Orlov and Rolle.

---

mora/service/association.py
mora/service/common.py
mora/service/employee.py
mora/service/engagement.py
mora/service/leave.py
mora/service/role.py
tests/test_integration_association.py
tests/test_integration_engagement.py
tests/test_integration_leave.py
tests/test_integration_role.py
tests/test_service_common.py

Refactored terminate implementation to be much less stupid.
Implemented termination of roles, which was missing for whatever reason.
Misc cleanup.

Edits now use datetime internally.

---

mora/service/common.py
mora/service/employee.py
mora/service/org.py
tests/test_integration_service.py

Added some tests and a fix for an edge case where we attempt to get an object outside of the validity period of its properties, but where metadata still exists at that given time.

Time machine

---

mora/lora.py
mora/service/address.py
mora/service/common.py
mora/service/details.py
mora/service/employee.py
mora/service/itsystem.py
tests/test_integration_itsystem.py

I haven't really cleaned this up; is it reviewable anyway?

Address refactor

---

mora/cli.py
mora/lora.py
mora/service/address.py
mora/service/association.py
mora/service/common.py
mora/service/details.py
mora/service/mapping.py
mora/util.py
src/employee/EmployeeDetailTabs.vue
src/organisation/OrganisationDetailTabs.vue
tests/fixtures/create_facet_tilknytningstype.json
tests/fixtures/create_klasse_medlem.json
tests/mocking/aabogade.json
tests/test_integration_association.py
tests/test_integration_importing.py
tests/test_integration_service.py
tests/test_lora.py
tests/util.py

Implements backend & frontend support for rendering addresses on associations.

#21700 association addresses

---

mora/converters/addr.py
mora/converters/importing.py
mora/service/address.py
mora/service/common.py
mora/service/details.py
mora/service/orgunit.py
mora/util.py
requirements.txt
tests/test_integration_address.py
tests/test_integration_association.py
tests/test_integration_importing.py
tests/test_integration_org_unit.py

This implements the server-side logic for specifying addresses when creating of organisational units. While at it, I cleaned up the handling of phone numbers ever so slightly.

#21879 orgunit addresses

---

mora/util.py
requirements-test.txt
tests/test_integration_itsystem.py
tests/test_integration_service.py
tests/util.py

Don't assume that LoRA is running in our default timezone.

#22078 timezone

---

mora/service/address.py
mora/service/employee.py
tests/test_integration_address.py

Address API adjustments

---

mora/service/employee.py

docs: correct address documentation for association, manager & role

---

mora/app.py
mora/service/address.py
mora/service/facet.py
mora/util.py
tests/test_integration_address.py

address: handle missing types

---

Jenkinsfile
conf.py
mora/app.py
mora/auth.py
mora/exceptions.py
mora/lora.py
mora/service/address.py
mora/service/common.py
mora/service/cpr.py
mora/service/details.py
mora/service/facet.py
mora/service/itsystem.py
mora/service/orgunit.py
mora/tokens.py
mora/util.py
mora/validator.py
requirements-test.txt
tests/test_auth.py
tests/test_integration.py
tests/test_integration_address.py
tests/test_integration_itsystem.py
tests/test_integration_org_unit.py
tests/test_integration_validator.py
tests/test_integration_writing.py
tests/test_lora.py
tests/test_service_address.py
tests/test_service_app.py
tests/test_service_common.py
tests/test_utils.py

This adds support for rejecting invalid termination requests, along with a few other, minor fixes.

#22325 validation of org. unit termination

---

tests/util.py

This should free the MO testsuite from relying on the LoRA internals.

tests: use test_base from LoRA

---

mora/service/org.py
package.json
src/components/InfoBox.vue
src/components/MoNavbar.vue
src/components/TheLeftMenu.vue
src/employee/EmployeeDetail.vue
src/employee/MoEmployeeWorkflows/MoEmployeeWorkflows.vue
src/organisation/MoOrganisationUnitWorkflows/MoOrganisationUnitWorkflows.vue
src/organisation/OrganisationLandingPage.vue
tests/test_integration_service.py
yarn.lock

add more icons to landing page

---

src/components/atoms/MoDatePicker.vue

This fixes unsetting the date in the picker.

properly handle null values in date picker

---

README.rst

Minor stuff related to spelling only

---

docs/index.rst

Update project name

---

.github/PULL_REQUEST_TEMPLATE.md

Add a strike through to the PR template

---

backend/mora/service/orgunit.py

23992: More documentation updates

---

NEWS.rst
frontend/package.json

Bumped version to 0.9.0. Updated NEWS.rst

---

NEWS.rst
backend/mora/exceptions.py
backend/mora/service/orgunit.py
backend/mora/validator.py
backend/tests/test_integration_org_unit.py

https://redmine.magenta-aps.dk/issues/24067

24067: Fixed so we are now able to edit root units

---

frontend/src/components/MoNavbar.vue

Added link for icon to redirect to the frontpage

---

frontend/src/components/MoPicker/MoAddressPicker.vue
frontend/src/components/MoPicker/MoEmployeePicker.vue
frontend/src/components/MoPicker/MoEngagementPicker.vue
frontend/src/components/MoPicker/MoFacetPicker.vue
frontend/src/components/MoPicker/MoItSystemPicker.vue
frontend/src/components/MoPicker/MoOrganisationPicker.vue
frontend/src/components/MoSearchBar/MoSearchBar.vue

Sorted dropdown lists

---

NEWS.rst
backend/mora/service/detail_writing.py

Fixed docs

---

frontend/src/components/MoTable/MoTable.vue
frontend/src/employee/EmployeeDetailTabs.vue
frontend/src/i18n/da/table_headers.json
frontend/src/organisation/OrganisationDetailTabs.vue

Added it tab for org and changed name

---

NEWS.rst
frontend/package.json

Amended previous version as 0.10.1 with updates to release notes

---

README.rst

- ~Have you performed a smoke test of the application?~
- ~Have you written tests for your changes?~
- ~Have you updated the release notes?~

fix build badges in README

---

frontend/build/webpack.base.conf.js
frontend/package.json
frontend/yarn.lock

Added babel polyfill to webpack config

---

docs/conf.py

~- [ ] Have you updated the documentation?~
~- [ ] Have you performed a smoke test of the application?~
~- [ ] Have you written tests for your changes?~
~- [ ] Have you updated the release notes?~

Added missing mock to sphinx conf.py

---

Jenkinsfile

jenkins: set a timeout for the warnings scanner

---

NEWS.rst
README.rst
backend/mora/settings.py
backend/mora/util.py

https://redmine.magenta-aps.dk/issues/25193
~- [ ] Have you written tests for your changes?~ (Not really testable)

Updated handling of settings files

---

frontend/e2e-tests/MoOrganisationUnitTree.js
frontend/src/components/MoTreeView/MoTreeView.vue
frontend/src/components/TheLeftMenu.vue

This branch contains a few follow-up fixes to the tree view.

#25579 race condition

---

backend/tests/fixtures/create_bruger_andersand.json
backend/tests/fixtures/create_bruger_andersine.json
backend/tests/fixtures/create_bruger_fedtmule.json
backend/tests/fixtures/create_facet_adressetype.json
backend/tests/fixtures/create_facet_enhedstype.json
backend/tests/fixtures/create_facet_tilknytningstype.json
backend/tests/fixtures/create_itsystem_ad.json
backend/tests/fixtures/create_itsystem_lora.json
backend/tests/test_integration_writing.py

Fix for test failures caused by changes in https://github.com/magenta-aps/mox/pull/100
:man_shrugging:

Attempt at fixing tests

---

backend/mora/cli/base.py
backend/mora/util.py
backend/tests/util.py
docs/conf.py
docs/cookbook.rst

This PR primarily expands on the documentation for the `full-run` command. In particular, it describes the go-to command for when it fails.

#26120 doc tweaks

---

backend/mora/service/detail_reading.py
backend/tests/test_integration_service.py

XXXXX: Quick reintroduction of the list_details endpoint.

---

NEWS.rst
frontend/e2e-tests/MoOrganisationUnitTerminate.js
frontend/src/views/organisation/workflows/MoOrganisationUnitTerminate.vue

https://redmine.magenta-aps.dk/issues/26890

fix details rendering in terminate unit dialog

---

NEWS.rst
frontend/e2e-tests/MoOrganisationUnitMapper.js
frontend/src/views/organisation/OrganisationDetailTabs.vue

https://redmine.magenta-aps.dk/issues/26898

ensure that we always display both units in a mapping

---

NEWS.rst
frontend/e2e-tests/MoEmployeeCreate.js
frontend/src/views/employee/MoEmployeeWorkflows/MoEmployeeCreate.vue
frontend/src/views/employee/MoEmployeeWorkflows/_store/employeeCreate.js

https://redmine.magenta-aps.dk/issues/25671
- ~[ ] Have you updated the documentation?~
- ~[ ] Have you written tests for your changes?~

25671: Fix adding proper organisation when creating new employees

---

frontend/src/views/organisation/workflows/MoOrganisationUnitCreate.vue

https://redmine.magenta-aps.dk/issues/27091

27091: Renamed the preset org unit address fixtures

---

NEWS.rst

27112: Updated NEWS.rst

---

NEWS.rst
frontend/src/api/OrganisationUnit.js
frontend/src/components/MoTreeView/MoTreeView.vue

https://redmine.magenta-aps.dk/issues/27155

 tree view: show all unit roots on reload

---

backend/mora/cli/base.py

Broken by my recent changes to LoRA, sorry…

full-run: fix injecting database contents

---

NEWS.rst
docs/dev/facets.rst
frontend/src/components/MoEntry/MoAddressEntry.vue
frontend/src/locales/da/input_fields.json
frontend/src/locales/da/table_headers.json
frontend/src/store/modules/facet.js
frontend/src/views/employee/EmployeeDetailTabs.vue
frontend/src/views/organisation/OrganisationDetailTabs.vue
frontend/src/views/organisation/workflows/MoOrganisationUnitCreate.vue

27431: Renamed 'address_property' facet to 'visibility' facet

---

NEWS.rst
frontend/src/store/modules/auth.js

27448: Fixed typo in auth.js causing redirect on 401 to break

---

backend/mora/service/detail_writing.py

Added support for 'force' on 'details/terminate'

---

NEWS.rst
backend/mora/common.py
backend/mora/mapping.py
backend/mora/service/orgunit.py
backend/tests/test_create_orgunit.py
backend/tests/test_integration_org_unit.py
backend/tests/test_integration_service.py
frontend/e2e-tests/MoOrganisationUnitCreate.js
frontend/e2e-tests/MoOrganisationUnitTerminate.js
frontend/src/components/MoEntry/MoOrganisationUnitEntry.vue
frontend/src/locales/da/input_fields.json
frontend/src/locales/da/shared.json
frontend/src/locales/da/table_headers.json
frontend/src/views/organisation/OrganisationDetailTabs.vue

https://redmine.magenta.dk/issues/27290

#27290 time planning

---

frontend/src/locales/da/alerts.json

Fixed comma

---

NEWS.rst
README.rst
backend/mora/service/address_handler/base.py
backend/mora/service/detail_writing.py
backend/mora/service/employee.py
backend/mora/service/handlers.py
backend/mora/service/orgunit.py
backend/requirements-docs.txt
docs/conf.py
docs/dev/configuration.rst

Fix RTD (development)

---

backend/requirements-test.txt

unittest-xml-reporting: avoid 2.3.x

---

.github/PULL_REQUEST_TEMPLATE.md

Below is a suggested update to the PR template.
I've primarily tried to capture the problems we've had with features not having been tested properly, and changes being introduced which change the underlying data model or API, without changes having been made to applications using our API.
---

Add updated PR template

---

backend/mora/service/address_handler/dar.py
backend/mora/service/address_handler/ean.py
backend/mora/service/address_handler/email.py
backend/mora/service/address_handler/phone.py
backend/mora/service/address_handler/pnumber.py
backend/mora/service/address_handler/www.py
backend/tests/test_address_handlers.py
frontend/src/locales/da/alerts.json

Add "force" override support to address validation.

---

NEWS.rst
frontend/src/locales/da/table_headers.json
frontend/src/views/employee/EmployeeDetailTabs.vue
frontend/src/views/organisation/OrganisationDetailTabs.vue

Feature/25416 engagement ID

---

README.rst

https://redmine.magenta-aps.dk/issues/28012
Denne PR tilføjer lidt grundlæggende dokumentation om vores udvidelser på datamodellen. Det er mestendels en genopstanden og tiljusteret udgave af den hidtidige dokumentation om det samme.
@istherepie Du får denne her til gennemsyn eftersom du er den primære modtager af denne dokumentation.
---

readme: document our new way of extending the LoRA database

---

NEWS.rst
backend/mora/cli.py
backend/mora/common.py
backend/mora/db_extensions.json
backend/mora/mapping.py
backend/mora/service/detail_reading.py
backend/mora/service/detail_writing.py
backend/mora/service/engagement.py
backend/tests/test_integration_engagement.py
backend/tests/test_integration_service.py

https://redmine.magenta-aps.dk/issues/28323
- https://redmine.magenta-aps.dk/issues/28361

Add 'fraction' field to engagements

---

backend/mora/service/detail_reading.py
backend/mora/service/detail_writing.py
backend/mora/service/engagement.py
backend/tests/test_integration_engagement.py

https://redmine.magenta-aps.dk/issues/28323

Fix bug where edit required 'fraction' to be boolean

---

NEWS.rst

Move manager inheritance to correct NEWS entry.

---

NEWS.rst
frontend/src/components/MoTreeView/MoTreeView.vue

https://redmine.magenta-aps.dk/issues/29603

Add spinner when tree view is loading

---

NEWS.rst
backend/setup.py
docs/conf.py
frontend/package.json

Hotfix release to fix building docs on RTD

Fix RTD build

---

NEWS.rst

Add AMQP NEWS entry

---

NEWS.rst
backend/mora/util.py
backend/tests/test_integration_address.py
backend/tests/test_integration_itsystem.py
backend/tests/util.py
frontend/e2e-tests/MoOrganisationUnitCreate.js
frontend/e2e-tests/support.js
frontend/src/api/OrganisationUnit.js
frontend/src/components/MoEntry/MoAddressEntry.vue
frontend/src/components/MoEntry/MoAssociationEntry.vue
frontend/src/components/MoEntry/MoEngagementEntry.vue
frontend/src/components/MoEntry/MoItSystemEntry.vue
frontend/src/components/MoEntry/MoLeaveEntry.vue
frontend/src/components/MoEntry/MoManagerEntry.vue
frontend/src/components/MoEntry/MoOrganisationUnitEntry.vue
frontend/src/components/MoEntry/MoRoleEntry.vue
frontend/src/components/MoPicker/MoOrganisationUnitPicker.vue
frontend/src/components/MoTreeView/MoTreeView.vue
frontend/src/views/employee/MoEmployeeWorkflows/MoEmployeeLeave.vue
frontend/src/views/employee/MoEmployeeWorkflows/MoEmployeeMove.vue
frontend/src/views/employee/MoEmployeeWorkflows/MoEmployeeTerminate.vue
frontend/src/views/organisation/workflows/MoOrganisationUnitCreate.vue
frontend/src/views/organisation/workflows/MoOrganisationUnitMove.vue
frontend/src/views/organisation/workflows/MoOrganisationUnitRename.vue
frontend/src/views/organisation/workflows/MoOrganisationUnitTerminate.vue

https://redmine.magenta-aps.dk/issues/30093

#29761 reorder date fields

---

backend/requirements-test.txt
backend/tests/test_cafe.py

https://redmine.magenta-aps.dk/issues/30899

#30899 run testcafe tests

---

frontend/src/modules/query/index.vue

fix download button (thanks Toke)

---

NEWS.rst
frontend/e2e-tests/MoOrganisationUnitCreate.js
frontend/e2e-tests/MoOrganisationUnitTerminate.js
frontend/src/components/MoEntry/MoAddressEntry.vue
frontend/src/components/MoEntry/MoEmployeeAddressEntry.vue
frontend/src/components/MoEntry/MoOrgUnitAddressEntry.vue
frontend/src/components/MoEntry/MoOrganisationUnitEntry.vue
frontend/src/components/MoPicker/MoFacetPicker.vue
frontend/src/locales/da/workflows.json
frontend/src/views/organisation/workflows/MoOrganisationUnitCreate.vue

https://redmine.magenta-aps.dk/issues/30094
---

#30094 orgunit address simplification

---

NEWS.rst
backend/mora/service/detail_reading.py
backend/tests/test_integration_itsystem.py

https://redmine.magenta-aps.dk/issues/31029

Handle orgfunk effects with more than one attribute virkning

---

docs/index.rst

https://redmine.magenta-aps.dk/issues/31547
---

Add links to LoRa and import-export docs to documentation index page

---

NEWS.rst
backend/mora/common.py
backend/mora/service/manager.py

https://redmine.magenta-aps.dk/issues/22316

Send proper deletion request to fix validation error.

---

NEWS.rst
backend/mora/service/orgunit.py
frontend/src/components/MoEntry/MoAddressEntry.vue
frontend/src/components/MoEntry/MoItSystemEntry.vue
frontend/src/components/MoEntryCreateModal.vue
frontend/src/store/modules/organisationUnit.js

https://redmine.magenta-aps.dk/issues/31851

Bugfix/31851 managers outside org unit validity 😦

---

NEWS.rst
frontend/e2e-tests/MoOrganisationUnitTerminate.js
frontend/src/views/organisation/workflows/MoOrganisationUnitCreate.vue

https://redmine.magenta-aps.dk/issues/29604

Redirect to page of newly created org unit

---

backend/mora/mapping.py
backend/mora/service/detail_writing.py
backend/mora/service/employee.py
backend/mora/service/handlers.py
backend/mora/service/manager.py
backend/mora/service/orgunit.py
backend/mora/triggers/__init__.py
backend/mora/triggers/internal/amqp_trigger.py
backend/tests/test_triggers.py

move RequestType so it can be imported in Triggers

---

NEWS.rst
frontend/src/components/MoTable/MoTable.vue
frontend/src/store/modules/organisationUnit.js

https://redmine.magenta-aps.dk/issues/29417

Prevent user from editing inherited managers

---

NEWS.rst
backend/mora/lora.py
backend/mora/service/facet.py

https://redmine.magenta-aps.dk/issues/32053

Remove limit when fetching klasser from facet

---

NEWS.rst
backend/mora/service/address_handler/base.py
backend/mora/service/address_handler/dar.py
backend/mora/service/address_handler/phone.py
backend/mora/service/address_handler/text.py
backend/tests/address_handler/base.py
backend/tests/address_handler/test_dar.py
backend/tests/address_handler/test_ean.py
backend/tests/address_handler/test_email.py
backend/tests/address_handler/test_phone.py
backend/tests/address_handler/test_pnumber.py
backend/tests/address_handler/test_text.py
backend/tests/address_handler/test_www.py
backend/tests/test_integration_org_unit.py
frontend/src/components/MoEntry/MoAddressEntry.vue

https://redmine.magenta-aps.dk/issues/32059

Add visibility support to every address type

---

backend/mora/__init__.py
backend/mora/app.py
backend/mora/lora.py
backend/setup.py
docker/Dockerfile

https://redmine.magenta-aps.dk/issues/28808

add /version endpoint

---

frontend/src/locales/da/alerts.json

error message for integration errors

---

NEWS.rst
frontend/src/components/MoEntry/MoOrganisationUnitEntry.vue

https://redmine.magenta-aps.dk/issues/30983

Fix OrgUnitEntry not taking current user settings into account
