- tests/util.py
Using a pipe can trigger a deadlock of the output from the child
process exceeds a certain limit, and we don't routinely flush/read the
pipe. Originally, we wanted to use a pipe so that we could detect when
the child was ready, and print its output.
We fix this by applying three changes:
1) Use an unnamed temporary file for output from the child.
2) Wait for the child process using the retry support in requests &
urllib3.
3) Flush the log file regularly, so we retain a reasonably ordering of
the output in reports from failing tests.
> tests: use a temporary file rather than a pipe

- tests/util.py
By using a single port, we should lessen the probability of hitting
the race condition where we allocate the same port for two concurrent
runs, allowing multiple concurrent builds on the builder with
reasonable stability.
> tests: use the same port for all LoRA integration tests during a run

- mora/service/common.py
- mora/service/itsystem.py
- mora/service/orgunit.py
- tests/test_integration_itsystem.py
- tests/test_service_common.py
Add a bit of type checking to the `addresses` field in org. units. Novik ran into this.
> Type checking

- mora/cli.py
- mora/service/address.py
- mora/util.py
- tests/test_integration_address.py
This fixes setting a different validity date on addresses when creating organisational units. The PR also includes another minor unrelated fix to logging I stumbled upon, and a change so that it's less likely that we target imports at the wrong location.
> #22274 orgunit address dates

- requirements-test.txt
- requirements.txt
The 0.5.7 release of pyexcel-io fixes loading CSV files from
directories containing '.' in their name, which was the motivation for
our fork.
See also <https://github.com/pyexcel/pyexcel-io/pull/47>.
> requirements: use just-released pyexcel-io v0.5.7

- mora/integrations/serviceplatformen.py
- mora/service/cpr.py
- mora/util.py
- tests/test_cpr.py
- tests/test_integration_employee.py
- tests/test_utils.py
By 'valid' we mean the ones that represent a valid date of birth.
> cpr test: only return something for valid CPR numbers

- mora/lora.py
- mora/service/address.py
- mora/service/common.py
- mora/service/details.py
- mora/service/employee.py
- mora/util.py
- tests/mocking/invalid-itsystem.json
- tests/mocking/reading-organisation.json
- tests/test_auth.py
- tests/test_integration_address.py
- tests/test_lora.py
- tests/test_reading.py
- tests/test_service_address.py
- tests/test_service_common.py
- tests/test_service_itsystem.py
- tests/test_utils.py
- tests/test_validator.py
This should properly remove the duplicates that we've run into, and
ensure that we only ever display entries that are properly current.
Ideally, we'd use the 'virkningstid' parameter to LoRA for this.
Unfortunately, the current code assumes that overriding 'virkningfra'
and 'virkningtil' in get() and fetch() work quite well. I fixed a few
issues, but the remaining ones were sufficiently annoying that I
simply opted for using a very small interval of one microsecond --
just like LoRA does, in fact.
> lora: use proper moment for 'now', if possible, rather than today

- src/components/atoms/MoDatePicker.vue
We simply use a ISO 8601 date, i.e. YYYY-MM-DD, without a timezone --
this ensures that we don't get any timezone-dependant logic.
> frontend: always use midnight as the time-of-day for validity periods

- mora/service/orgunit.py
- tests/test_integration_address.py
- tests/test_integration_association.py
- tests/test_integration_importing.py
- tests/test_integration_manager.py
- tests/test_integration_org_unit.py
- tests/test_integration_service.py
We generally only return the current validity, on the general
assumption that this will span a sufficiently long interval.
This change supersedes #114.
> include validity when returning organisational units

- mora/exceptions.py
- mora/service/common.py
- mora/validator.py
- tests/test_integration_org_unit.py
- tests/test_integration_service.py
make parent validity check more robust  …
This should ensure that a 'candidate parent' is properly valid:
1. It's valid at the exact time of the move.
2. Neither it, nor any parent, belongs to another organisation.
3. We are not creating a cycle.
Test #1 was failing, previously. In fixing I tried to make the
validation routine more robust and readable, adding #2 and
strengthening #3 to check for preëxisting cycles.
The root cause of bug #23182 was that the check didn't use
`common.is_reg_valid()` but instead rolled its own not-quite-as-robust
check, resulting in a move to a unit at an invalid date giving the
wrong error.
> #23182 parent checks

- mora/exceptions.py
- mora/service/orgunit.py
- mora/validator.py
- src/i18n/da/alerts.json
- src/organisation/MoOrganisationUnitWorkflows/MoOrganisationUnitTerminate.vue
- src/validators/DateInRange.js
- tests/test_integration_org_unit.py
This PR makes the error message for termination lie less; previously,
it'd claim the date was too early even if it was, in fact, too late.
Instead, we just re-use the message saying that the date is outside
the validity of the unit. Since we were doing that, I consolidated the
termination check into the validity check, and added a frontend
validation instead, since they're generally nicer and more immediate.
> #23172 proper termination error

- config/index.js
You can now set `BASE_URL` to point to the preëexisting MO instance when
running the frontend dev server. It's similarly used when setting the
target of the TestCafé tests.
> config: reset default proxying URL to localhost:5000, with override

- mora/integrations/serviceplatformen.py
- tests/test_cpr.py
This fixes, or rather, works around a few issues on our demo and test
servers. Unborn employees as well employees born in the 19th century
will almost certainly not occur in actual deployments, unless we get
extreme historic data. In that case, we'll fix whatever issues crop
up.
When testing, however, people often enter an arbitrary number, not
knowing that the CPR number actually corresponds to someone either
born in the future or in the century prior to last. Since this may
cause issues, we should simply report that nothing was found.
> #23449 dummy cpr dates

- package.json
- tests/test_cafe.py
- tests/util.py
This should truly fix the LoRA testsuite, as it doesn't build the MO
frontend -- nor should it.
> tests: skip TestCafé tests when requirements not satisfied

- mora/service/details.py
- mora/service/manager.py
- src/components/MoEntry/MoManagerEntry.vue
- src/components/MoLink.vue
- src/components/MoPicker/MoManagerAddressPicker.vue
- src/employee/EmployeeDetailTabs.vue
- tests/test_integration_manager.py
- tests/test_integration_service.py
This PR brings manager addresses to the point where they _mostly_ work. It adjusts the code so that the backend renders arrays for manager addresses, and the frontend code (slightly) so that it actually uses these arrays. I've also adjusted the fields in the frontend so that they correspond to what the backend returns.
> #23781 manager address backend

- backend/mora/app.py
- backend/tests/test_cafe.py
- backend/tests/test_sso.py
- backend/tests/util.py
- docs/vuedoc/MoAddressPicker.md
- docs/vuedoc/MoEmployeePicker.md
- docs/vuedoc/MoEngagementPicker.md
- docs/vuedoc/MoFacetPicker.md
- docs/vuedoc/MoItSystemPicker.md
- docs/vuedoc/MoOrganisationPicker.md
- docs/vuedoc/MoSearchBar.md
- frontend/e2e-tests/MoEmployeeCreate.js
- frontend/e2e-tests/MoEmployeeLeave.js
- frontend/e2e-tests/MoEmployeeMove.js
- frontend/e2e-tests/MoEmployeeMoveMany.js
- frontend/e2e-tests/MoEmployeeTerminate.js
- frontend/e2e-tests/MoOrganisationUnitCreate.js
- frontend/e2e-tests/MoOrganisationUnitMove.js
- frontend/e2e-tests/MoOrganisationUnitRename.js
- frontend/e2e-tests/MoOrganisationUnitTerminate.js
This PR changes the TestCafé tests so that they validate that the corresponding actions actually succeed, by checking the log. It turns out that some of the operations _didn't_ do so, due to changes made by earlier tests. To fix this, I changed our test runner to reset the DB between each test — this is significantly slower, but more thorough and reliable.
I was motivated for this by a change that _ought_ to break the tests — but didn't.
https://redmine.magenta-aps.dk/issues/24386
---
> #24386 TestCafé results

- backend/mora/cli.py
This should make it easier for development -- and frontend developers
in particular -- to write tests that assume the initial test layout.
The command as such is mostly an evil hack, but it works.
> add cli command to run MO with a test-like database

- NEWS.rst
- backend/tests/test_docs.py
https://lorajenkins.magenta.dk/job/LoRa/job/PR-73-head/1/testReport/junit/tests.test_docs/Tests/test_is_vuedoc_uptodate/
> hotfix: add a check for vuedoc.md to unbreak to mox testsuite

- NEWS.rst
- backend/mora/service/address.py
- backend/mora/settings.py
- backend/tests/mocking/aabogade.json
- backend/tests/mocking/dawa-addresses.json
- backend/tests/mocking/dawa-autocomplete.json
- backend/tests/mocking/many-addresses.json
- backend/tests/mocking/update-fixture.py
- backend/tests/test_integration_address.py
- backend/tests/test_integration_manager.py
- backend/tests/test_service_address.py
- backend/tests/util.py
https://redmine.magenta-aps.dk/issues/24077
This change adds support for DAWA access addresses — _adgangsadresser_ — to autocomplete and rendering. It also adds a fallback to historic entries, although they differ slightly from current addresses as they may omit the coordinates; in this case, we omit the OSM link.
> #24077 access address

- NEWS.rst
- frontend/e2e-tests/MoEmployeeCreate.js
- frontend/src/components/MoPicker/MoAddressPicker.vue
- frontend/src/locales/da/input_fields.json
Everything else just works, but it's no longer styled like an error. I also added a test.
> adjust styling and text for “no addresses” note

- backend/tests/util.py
We have `test_support` now; anything that touches LoRA internals
belongs there, so that we can modify it exclusively upstream.
> tests: remove patching that belongs in LoRA upstream

- NEWS.rst
- frontend/e2e-tests/MoOrganisationUnitMapper.js
- frontend/src/api/HttpCommon.js
- frontend/src/modules/organisationMapper/_store/index.js
- frontend/src/modules/organisationMapper/index.vue
https://redmine.magenta-aps.dk/issues/26402
https://redmine.magenta-aps.dk/issues/27228
This PR addresses two bugs in the organisation mapper. #27228 fixes so that we report successful saves. Errors, however, don't work _terribly_ well, but AFAICT that's a persistent issue throughout the UI. I stumbled upon a fix for #26402, so I fixed that one as well; this makes it so the save button correctly disables after a save.
> #27228 & #26402 mapping fixes

- frontend/e2e-tests/MoEmployeeAssociationTab.js
- frontend/e2e-tests/MoOrganisationManagerTab.js
This just fixes a minor oversight when updating #317; tests now require an extra call to reset the database. This relies on an endpoint available both during the test run and the `full-run`, and invoked after each test. I'd like to have it invoked _before_, but ran into some issues with early queries failing.
> e2e-tests: ensure that we reset database in the tab tests

- Jenkinsfile
The current deployment setup is too unstable, so it will be removed
until it can be replaced with the new Gitlab setup
> Remove Jenkins deployment hook

- NEWS.rst
- frontend/src/views/organisation/workflows/MoOrganisationUnitTerminate.vue
The frontend doesn't actually know when a given unit terminates;
rather it knows how long the current values remain unchanged.
Restricting termination dates to those values prevents terminating a
unit after the next change in its properties.
Rather, we simply allow selecting _any_ termination date in the
future. Should the user pick a date where a unit no longer exists,
they can't pick that unit. Should they pick a unit, and _then_ pick a
date, the unit will simply deselect if it no longer exists.
https://redmine.magenta-aps.dk/issues/29669
> terminate: don't restrict termination dates beyond now and onwards

- NEWS.rst
- frontend/src/components/MoInput/MoInputDate.vue
This changes is so that we focus the current date in dropdowns where that's the minimum valid value. I'm not entirely certain that this was the issue in the reported bug, but it's a major annoyance and my best guess.
Previously, the date picker would always pop up to the current value, even when that value was disallowed. Instead, clamp whatever we display to the allowable values. With our test data, this avoids the need for flipping from somewhere in the sixties to today in certain circumstances. That's just obnoxious…
https://redmine.magenta-aps.dk/issues/29700
> #29700 focus current date in dropdowns

- backend/requirements-docs.txt
- docs/conf.py
I noticed that the docs lacked the CLI documentation.
---
> docs: fix generating CLI docs; use mock

- NEWS.rst
- backend/mora/service/address.py
- backend/mora/service/engagement.py
- backend/mora/service/handlers.py
- backend/tests/test_integration_engagement.py
This change ensures that we validate addresses not only on creation, but also when editing. During fixing this bug, I noticed that `engagement` had a possible bug where we validated w.r.t. to previous values during editing.
https://redmine.magenta-aps.dk/issues/29569
> #29569 validate address when editing

- NEWS.rst
- backend/mora/service/orgunit.py
- backend/mora/service/validation/validate.py
- backend/mora/service/validation/validator.py
- frontend/src/api/Validate.js
- frontend/src/components/MoPicker/MoOrganisationUnitPicker.vue
- frontend/src/validators/MovableOrgUnit.js
- frontend/src/vee.js
- frontend/src/views/organisation/workflows/MoOrganisationUnitMove.vue
This fixes a race condition where we ran the validators before emitting the event that effected the change to the validated field. As a result, the dialog would always validate the _previous_ value of the field. In most cases, you wouldn't notice this, but you would for the initial input, where there was no previous value.
Since this was rather hard to track down, I fixed a few other bugs while at it. I made sure that we write the error above root units below the actual root unit, and applied a minor change to prevent moving a selecting the same source and destination.
https://redmine.magenta-aps.dk/issues/29570
---
> #29570 move validations

- NEWS.rst
- backend/mora/service/address.py
- backend/mora/service/association.py
- backend/mora/service/employee.py
- backend/mora/service/engagement.py
- backend/mora/service/itsystem.py
- backend/mora/service/leave.py
- backend/mora/service/manager.py
- backend/mora/service/orgunit.py
- backend/mora/service/role.py
- backend/tests/test_integration_address.py
- backend/tests/test_integration_org_unit.py
All handlers now take 'org' as an optional parameter, which is
alternatively looked up from the cache, so we never fetch from LoRa
https://redmine.magenta-aps.dk/issues/31661
> Streamline how various request handlers use the 'org' parameter

- NEWS.rst
- frontend/src/components/MoEntryTerminateModal.vue
The modal now also correctly responds to errors from the backend.
https://redmine.magenta-aps.dk/issues/29548
> Prevent user from terminating managers before they are active.

- NEWS.rst
- frontend/src/components/MoEntry/MoEntryBase.js
- frontend/src/components/MoEntry/MoOrganisationUnitEntry.vue
- frontend/src/components/MoEntryEditModal.vue
Adding the user key when creating org units is still possible
https://redmine.magenta-aps.dk/issues/32048
> Prevent user from editing user key on org units

- NEWS.rst
- backend/mora/exceptions.py
- backend/mora/service/address.py
- backend/mora/service/association.py
- backend/mora/service/employee.py
- backend/mora/service/engagement.py
- backend/mora/service/handlers.py
- backend/mora/service/itsystem.py
- backend/mora/service/leave.py
- backend/mora/service/manager.py
- backend/mora/service/orgunit.py
- backend/mora/service/related.py
- backend/mora/service/role.py
- backend/mora/service/validation/validator.py
- backend/tests/test_integration_association.py
- backend/tests/test_integration_employee.py
- backend/tests/test_integration_engagement.py
- backend/tests/test_integration_itsystem.py
- backend/tests/test_integration_leave.py
- backend/tests/test_integration_manager.py
- backend/tests/test_integration_org_unit.py
- backend/tests/test_integration_related_units.py
- backend/tests/test_integration_role.py
- backend/tests/test_integration_termination.py
- backend/tests/test_validator.py
- frontend/src/components/MoEntryEditModal.vue
I basically undid the specific changes made in the previous feature.
I've also optimized imports in the files I touched.
https://redmine.magenta-aps.dk/issues/32476
> 32476: Re-enable functionality to edit the past
